### ISSUE TITLE
flex-shrink对img无效？

### ISSUE THREAD

**Issue by yongningfu** [gmfe/Think#14]
大概意思是：flex 对 img标签 可以放大 但是无法缩小

具体demo

缩小出问题: [demo](https://jsfiddle.net/fuyongning/fhefq1d8/)

放大： [demo](https://jsfiddle.net/fuyongning/54hryub9/)

**Comment by yongningfu** [comment]
@liyatang 大佬有想法么？

**Comment by yongningfu** [comment]
在缩小那里，每个图片设置成500px，容器只有100px，发现没有缩小

**Comment by liyatang** [comment]
我这里是缩小的

![image](https://user-images.githubusercontent.com/1010130/32283209-bac3be42-bef1-11e7-851b-445997a54956.png)
